#!/bin/python

#### Python script to calculate the progress of the probabilistic insurance calculator


#### Import statements
from pathlib import Path


#### Count number of parquets generated by the OQ calc
path_parq, ext_parq = '/scratch/parquet-out/current/', '.parquet'
num_parqs = sum(1 for f in Path(path_parq).glob(f"*{ext_parq}") if f.is_file())


#### Count current number of output files in the ins-out folder for this calc
path_ins = '/work/CanadaSRM-output/probabilistic/current/ebRisk/ins-out/'
file_ins = f"Shake_by_LOB_{CALCID}_2026*.csv"
num_outs = sum(1 for f in Path(path_ins).glob(file_ins) if f.is_file())


#### Return progress
perc_complete = (num_outs/num_parqs)*100
print(f"Insurance Calc is {perc_complete:.0f}% done.")
