# INITIALLY Generated automatically with manyFaults.py on: 2025-05-29 08:25:29.433570
[general]
description = Montreal M5-7.5 events, based on the 1732 event at 45,5 N, 73,6 W. Hypocentral depth of 10km (GSC). Using representative azimuth of St Lawrence Valley, based on Lamontagne et al., (2000, EOS), to represent Iapetan Rift. Specifically, str/dip/rake of 040/75/90 from Tremblay et al., (2003, Tectonophysics).
calculation_mode = scenario_risk
random_seed = 113

[Exposure model]
exposure_file = ../../../CanadaSRM-input/current/exposure/oqBldgExp_CA_2025Update.xml

[site_params]
site_model_file = ../../../CanadaSRM-input/current/geotech/site-vgrid_CA.csv

[Rupture information]
rupture_model_file = ../../../CanadaSRM-code/scenario/ruptures/ruptures/rupture_SCM5p8_MontrealIapetan.xml
rupture_mesh_spacing = 4

[Calculation parameters]
gsim_logic_tree_file = ../../../CanadaSRM-input/current/hazard/gmms/LogicTree/OQ_classes_NGASa0p3weights_stablecrust.xml
truncation_level = 3.0
maximum_distance = 600
number_of_ground_motion_fields = 200

[Vulnerability]
taxonomy_mapping_csv = ../../../CanadaSRM-input/current/vulnerability/CanSRM1_TaxMap_b0.csv
structural_vulnerability_file = ../../../CanadaSRM-input/current/vulnerability/vulnerability_structural_CAN.xml
nonstructural_vulnerability_file = ../../../CanadaSRM-input/current/vulnerability/vulnerability_nonstructural_CAN.xml
contents_vulnerability_file = ../../../CanadaSRM-input/current/vulnerability/vulnerability_contents_CAN.xml
occupants_vulnerability_file = ../../../CanadaSRM-input/current/vulnerability/vulnerability_occupants_CAN.xml

